# Generated by Django 3.2.9 on 2022-09-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('rub', 'RUB')], max_length=3),
        ),
    ]
